apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: efk-space
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    nodePort: 31000
    targetPort: 5601
  selector:
    app: kibana
